AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template for Infrastructure'
parameters:
  Envname:
    Type: String
    description: 'Environment name (e.g votre identifiant sans learning)'
    Default: 'learnaws_sbikozi'
  BucketName:
    Type: String
    Description: "S3 bucket name (e.g votre identifiant sans learning)"
    Default: "s3-bucket-trigger-lambda"

Resources: 
## IAM Role pour la fonction lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Envname}-LambdaExecutionRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: [sts:AssumeRole]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub '${Envname}-LambdaS3AccessPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub 'arn:aws:s3:::${Envname}-${BucketName}/*'
# Fonction lambda pour gerer les event S3
  LambdaTrigger:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${Envname}-${BucketName}'
      Handler: main.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.12
      Code : ../src
 
# s3 bucket pour le stocker les fichiers
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${Envname}-${BucketName}'
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt LambdaTrigger.Arn